name: Update AFD Sponsors

# 爱发电 Webhook 会发 repository_dispatch 事件触发
on:
  repository_dispatch:
    types: [rebuild]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm run fetch-afd
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/.vuepress/public/data/afd-sponsors.json'
          message: 'chore: update sponsors [skip ci]'
      - name: Trigger Vercel Deploy
        run: curl -X POST ${{ secrets.VERCEL_BUILD_HOOK }}